name: Hello World Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello World
        run: |
          echo "Hello, World!"
          echo "Running from GitHub Actions!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"

      - name: Node Version
        run: node --version

      - name: Current Time
        run: date
